project:
  type: website

website:
  description: "Notes on prue mathematics, systems programming and game theory"
  site-url: https://menshikow.github.io
  title: "notes by menshikow"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter-x
        href: https://x.com/menschikowan
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
